### ISSUE TITLE
Not showing stack size for all NPCs anymore

### ISSUE THREAD

**Issue by ShrrgWolf** [alexanderhenne/external-plugins#2]
I think a commit was just made that makes the plugin not take effect until you damage the NPC. I used the plugin both for stack information and to also just highlight the southwest tile of ALL npcs regardless of if i had damaged them. Can you make a checkbox that toggles the ability for it to be always on or only on when the NPC is damaged?

**Comment by alexanderhenne** [comment]
Which NPCs were you using it on?

**Comment by ShrrgWolf** [comment]
Every NPC, i use it on farm runs so its easier to see. For instance the squirrels on fossil island next to the hardwood grove because they are so small, puffer fish underwater next to seaweed patches. Finding imps in the overworld as they are also tiny. I just use it for all NPCs

**Comment by ShrrgWolf** [comment]
I set the min stack size to 1 so it activated for all NPCs

**Comment by alexanderhenne** [comment]
I won't add it back for every NPC, it allowed people to abuse it by seeing the real position of boss NPCs for example

**Comment by ShrrgWolf** [comment]
I respect your decision. Why is seeing the real position of boss NPCs abuse? To me that would show the direction its walking and thats about it.

**Comment by ShrrgWolf** [comment]
Also would it be possible for it to deactivate when in bossing areas but activate outside of them?
