### ISSUE TITLE
Only on certain NPCs change

### ISSUE THREAD

**Issue by thebubbsy** [alexanderhenne/external-plugins#3]
I ask you please reconsider the change you made recently which only allowed this plugin to work on dust devils and the mm1+2 Monkeys. This is used in barrage slayer, its especially useful for abby demon bursting.

Please see my video regarding it here: https://www.youtube.com/watch?v=OPue1AzqhnA

**Comment by alexanderhenne** [comment]
Which NPCs do you want it to work with? Hand me a list and I'll add them

**Comment by thebubbsy** [comment]
Abyssal demon, Greater Nechryael, dust devil, smoke devil.
(and all of their slayer superior varients): Choke devil, Nechryarch, Greater abyssal demon, Nuclear smoke devil.

And barrage Tzhaars is fairly common slayer task too:
TzHaar-Hur, TzHaar-Mej, TzHaar-Ket, TzHaar-Xil

Thanks!

**Comment by Wynadorn** [comment]
Maybe every mob in the catacombs could be listed,
personally I'd like to see Warped Jelly and Dagganoths added

Edit: How about a blacklist?
