### ISSUE TITLE
NPC indicators overlap

### ISSUE THREAD

**Issue by ShrrgWolf** [alexanderhenne/external-plugins#4]
in a previous answer you said **I won't add it back for every NPC, it allowed people to abuse it by seeing the real position of boss NPCs for example** but by highlighting the boss NPCs through NPC indicators you can see their real position you just need type the NPC name in so disabling the ability to show the real position of all NPCs in the monkey meterics plugin doesnt change what people can do it just takes extra steps.

**Comment by alexanderhenne** [comment]
This plugin is really only for chinning/bursting so it doesn't make sense to show it for every NPC
